# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        ## 使用联系人权限（根据需要启用）
        'PERMISSION_CONTACTS=0',

        ## 相机权限
        'PERMISSION_CAMERA=1',

        ## 麦克风权限
        'PERMISSION_MICROPHONE=1',

        ## 语音识别权限（如果需要语音控制或字幕）
        'PERMISSION_SPEECH_RECOGNIZER=1',

        ## 照片权限（如果需要访问或保存图片/视频）
        'PERMISSION_PHOTOS=1',

        ## 定位权限（后台定位与用户位置信息）
        'PERMISSION_LOCATION=1',
        'PERMISSION_LOCATION_WHENINUSE=1',

        ## 通知权限（推送通知支持）
        'PERMISSION_NOTIFICATIONS=1',

        ## 媒体库权限（访问音乐和视频库）
        'PERMISSION_MEDIA_LIBRARY=1',
      ]
    end
  end
end
